spring.application.name=bigburger


# Configuración de la base de datos
spring.datasource.url=${BDURL}
spring.datasource.username=${BDUSERNAME}
spring.datasource.password=${BDPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

security.jwt.key.private=${USERGENERATOR}
security.jwt.user.generator=${JWTKEY}

app.base-url=http://localhost:8080