spring.application.name=bigburger


# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bigburger?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Peliculajc46
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

security.jwt.key.private=67c70c01b7350eab7fa1ea53fa7271d8c1ab72374136c44354a4a0006fd93499
security.jwt.user.generator=AUTHUSER_BACKEND_BIGBURGER2025